version: '3.9'
services:
  web:
    container_name: wallet-backend
    hostname: wallet-backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - caddy

networks:
  caddy:
    external: true